"""
协作策略模块 - 多Agent协作模式（已合并：strategies.py 包含全部协作逻辑）
"""

from .strategies import (
    CollaborationResult,
    BaseCollaborationStrategy,
    PipelineStrategy,
    MasterSlaveStrategy,
    ReviewStrategy,
    AuctionStrategy,
    HybridStrategy,
    LLMReflection,
    ReflectionTrigger,
    ReflectionDecision,
    ReflectionResult,
    ReflectionPrompt,
    AdaptivePipelineWithReflection,
    ResultAggregator,
    PartialResult,
    AggregationStrategy,
    ComplexCollaborationEngine,
    CollaborationMode as ComplexCollaborationMode,
    DynamicTeamForming,
    TaskAuction,
    ConsensusMechanism,
    KnowledgeSharing,
    SimpleAggregator,
    WeightedVoteAggregator,
    HierarchicalAggregator,
    LLMAggregator,
    MasterAgentAggregator,
)

__all__ = [
    "CollaborationResult",
    "BaseCollaborationStrategy",
    "PipelineStrategy",
    "MasterSlaveStrategy",
    "ReviewStrategy",
    "AuctionStrategy",
    "HybridStrategy",
    "LLMReflection",
    "ReflectionTrigger",
    "ReflectionDecision",
    "ReflectionResult",
    "ReflectionPrompt",
    "AdaptivePipelineWithReflection",
    "ResultAggregator",
    "PartialResult",
    "AggregationStrategy",
    "ComplexCollaborationEngine",
    "ComplexCollaborationMode",
    "DynamicTeamForming",
    "TaskAuction",
    "ConsensusMechanism",
    "KnowledgeSharing",
    "SimpleAggregator",
    "WeightedVoteAggregator",
    "HierarchicalAggregator",
    "LLMAggregator",
    "MasterAgentAggregator",
]
